import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "../auth";
import LoginPage from "@/components/login-page";
import SignOut from "@/components/sign-out";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-cyan-50`}
      >
        {!session || !session.user ? (
          <LoginPage />
        ) : (
          <div className="flex flex-col min-h-screen font-[family-name:var(--font-geist-sans)] bg-gradient-to-r from-cyan-500 to-cyan-600">
            <nav className="flex px-10 py-3 gap-6 items-center justify-between bg-transparent">
              <h1 className="text-3xl font-semibold text-white">ReadSphere</h1>
              <span className="flex gap-4 items-center">
                <Image
                  src={session.user.image ?? ""}
                  alt={session.user.name ?? ""}
                  width={36}
                  height={36}
                  className="rounded-full border-2 border-white"
                />
                <SignOut />
              </span>
            </nav>
            <main
              className="flex flex-col gap-10 px-8 py-6 sm:px-16 sm:py-12 grow"
              style={{}}
            >
              {children}
            </main>
            <footer className="flex justify-center items-center p-6 bg-gradient-to-r from-cyan-500 to-cyan-600">
              <p className="text-white text-sm">
                © 2025 ReadSphere. All rights reserved.
              </p>
            </footer>
          </div>
        )}
      </body>
    </html>
  );
}
